"use client"
import { El_Messiri } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import Footer from "./__component/Footer/Footer";
import Navbar from "./__component/Navbar/Navbar";
import { store } from "./rtk/store";

const el_Messiri = El_Messiri({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
                <html lang="en">
      <body className={el_Messiri.className}>
        <Navbar />
        {children}
          <Footer />
        </body>
    </html>
    </Provider>
  );
}
